language: scala

before_install:
  - openssl aes-256-cbc -K $encrypted_2197b9b29ce6_key -iv $encrypted_2197b9b29ce6_iv -in .travis/secret-key.asc.enc -out .travis/secret-key.asc -d
  - echo $PGP_PASSPHRASE | gpg --passphrase-fd 0 --batch --yes --import .travis/secret-key.asc

install:
  - pip install --user codecov

scala:
  - 2.12.10
  - 2.11.12

jdk:
  - openjdk8

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"

stages:
  - name: check
  - name: test
  - name: release
    if: (branch = master AND tag IS present)

jobs:
  include:
    - stage: check
      script:
        sbt headerCheck scalafmtCheckAll
    - stage: test
      script:
        - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
        - if [[ "$TRAVIS_SCALA_VERSION" == 2.12.* ]];
          then
            sbt ++$TRAVIS_SCALA_VERSION coverageReport && codecov;
          else
            echo "Skipping coverage report for Scala != 2.12.x";
          fi
    - stage: release
      script:
        sbt +clean +publishSigned sonatypeReleaseAll

env:
  global:
    # PGP_PASS
    secure: yhVxLgN0NHoDtNyZ2JeHQkHOMsv1k4ariPfIY48q7PjqthbiYRQlONWen/TF0dJwc3FKQiJsXcoWiV63miaDYd8CaATlXtV20+oWN8storbgzN0U64lbX055ZYHAbgpX+GSAcc8OqE+tuWkp7S2+Gp4FLuXuKgMcly76iaiHyRezaRcMr9xzZ/otxBnz5qJvyjAMzlmNGKii0KcWndNJ+7+Mpryhj1BPcDbOnPcFTyTX9W1P+hBTxGPF9NfMgbjC4ClT2JYMh208pDjoeuJVgj2psOcRnOtE+fYBCkMB013jgGH+oMQ2gd59iDn9SkaAOwP7Cinlwtg9KRMpw0m3d+MWqMRuNE1dDJO//+0dTU1V2IHAs8Y0QTu9piwTbx1fS0uVTxNtli1s4mN2/hgC+reklFGv8EfwaP/+/RdkUUDQfj8G0Pmb+ElWRLOFBTYSfFWTRHBsAbq9eE+UmSI8/ocKw2t0INQO5w1/rr7qT4pKtjtKnSV61iJwbMvQ2aawomPCpIkvCWUwUo+PKJw6uQ6eoceU+7zdyc5YinRlYpchGjzyqxe+0T7FxE+9r8MW0BpzM4mbQcSiii5lg5lkchbWLvhVavId6dx8Of3r64jA6LL067igIuz8PdSOHWHxjcQ3zQVmagB5EJYcv/hCaprwMm0hxZ9wfJEqbdE8JCs=
    # SONATYPE_USERNAME
    secure: T7CrLrUPhBqUmyFEF/i0x1wkeWy5WkQfji7xeDJAuIhCPBp1V0wCEQqViUD1ojs/ClcurBI/aAKVjh/k99/D28ZUXFQ2WfMp2dpi0T9cxHMpqkUt3r/stl9Rvo8KfqF0rrPJOoRpWRkJg8b/RgjDAnZnDH1UGmkn9tNFnZBcUw/9/9wlAGuhZnkxWIw/ZGjSXnLlQnc8w8pLjibuqS58yKRNsJtOHvr2oQlg31rhwF+xy0R5HeT/htUkvUFq+LcdiqL7Q0kjTUNCxfPQ26ahhKttOIQVeoyFtDKUhJ2mAfOH9v2iC0zqrHt7a4oIPcqaG5FiHjZP0l9sXdUHpZAp18p5oP3k81SyRfgfL0mja0WI74XSnoeY2njFLpK4Hfq9I1RSzeaEdM5kU+P4gDpFOYH+nagq9cZKEcpSIdHyO9SBLbSRQ1ifpvrUAfPeJEybQoYSzWQDxFOvWfFjBWHq6MAib6ocxQtJJqDJMSdLXLiWhZIzamI7o9Kose8CzcOowE74oc9OJ79NMxAycMO1D1k/l/OUm/naGc5JbhU2yYbGQABxdDVwkumZvQtLlMwN0QBIzk+iCQ3krd4KSiXQpt9OgjAIPmSmp0EOTR6CwPNFrC7OCY95p5jjGcE0tnaR/czGs7mMWHjvMlOZq3WUURKybffbCQCm3mkoNZzdyIc=
    # SONATYPE_PASSWORD
    secure: eh3lVMgtBSlvaGs+iL5IulEWk6oerkEw1QmslOwzZfK5MjkdTC51orqCGz0t1R3iu7gpX7NkEFtiCXSB+Tpn7L3Yl2FjNJ/I4HvaOggys6Xc6TtvQYdFIzdkxNau4wDKx/H0NqE9UNx25DAvun+WVfnxJNKDsrtaY0mI07DmuP9o2peX44YYiTzMW3zwDW7ZG5zl9QiCq7LugCoJM+pM1Wr68jDN0HAB/YLToWaRefH3S2jZ2rZ/fCHorjo0kfaWzzQUCRe3xFEqhf49Zry9V18FW8oyVI0t7XdjxELoWXIe9noZrZpm4zIEpeg42TKtOjca92HFycesq7qXNXX1PhrNdzAESAme3tzAzcGvzh5uOuzk63lZf/dx/hW1eej9eiHl4nXaJaS/Fdy+YvOFjifGACK26K2VnX4eNPlQidK0rl9jcaRn4jdFYHzAeI7oF2MDlpKSQfemVgo7gDe0ieOAKYIjyIrtSShvXCB+I9c/SXkMZqd332hic+kp2U4yjSqWhXZojYUhcacb80nRMeyzVrDgIZZWJKySP5+6pxQ0Xqd3Wisp+6wYkgCauvNZn1GGJ4Q11VVyy1pE456iBlQ0moKE93Y/1Xe1J4YHDfgIHDnVA5S2BvrzmZRcFcxtZZl0sx8OzjjVuAzRDfB7kn8cfxzfzZFLTvbd4MNt0aQ=
