language: scala

install:
  - pip install --user codecov

scala:
  - 2.12.10
  - 2.11.12

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
  - if [[ "$TRAVIS_SCALA_VERSION" == 2.12.* ]];
    then
      sbt ++$TRAVIS_SCALA_VERSION coverageReport && codecov;
    else
      echo "Skipping coverage report for Scala != 2.12.x";
    fi
